title: "Microsoft Azure Tech Intensity Workshop"
logo: "/img/tiw-logo.png"
remote_theme: pmarsceill/just-the-docs
search_enabled: true
footer_content: Azure is a registered trademark of Microsoft Corporation. Copyright &copy; 